# Server
server.port=8081

# Application Name
spring.application.name=User Management API

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/user_management
spring.datasource.username=root
spring.datasource.password=@$KRAnth!18
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=O*O_85!nEDL4*=B.;2Lo{Myeu()O-GC#B}zo:3P-<N4
jwt.expiration=3600000

# Logging
logging.level.root=WARN
logging.level.com.example.usermanagement=INFO